export const game = [
  // day #1
  [
    {
      word: "woo",
      hint: "stir frying pan",
      answer: "wok",
      alteredPosition: 2,
    },
    {
      word: "wok",
      hint: "took the championship",
      answer: "won",
      alteredPosition: 2,
    },
    {
      word: "won",
      hint: `dramatic cry: "___ is me!"`,
      answer: "woe",
      alteredPosition: 2,
    },
    {
      word: "woe",
      hint: "long-handled farm tool",
      answer: "hoe",
      alteredPosition: 0,
    },
    {
      word: "hoe",
      hint: "move like a kangaroo",
      answer: "hop",
      alteredPosition: 2,
    },
    {
      word: "hop",
      hint: `after "alley" in basketball`,
      answer: "oop",
      alteredPosition: 0,
    },
    {
      word: "oop",
      hint: `pairs with an audience "aah"`,
      answer: "ooh",
      alteredPosition: 2,
    },
    {
      word: "ooh",
      hint: `modeling toy: play-___`,
      answer: "doh",
      alteredPosition: 0,
    },
    {
      word: "doh",
      hint: "Lassie is one",
      answer: "dog",
      alteredPosition: 2,
    },
    {
      word: "dog",
      hint: "gear tooth",
      answer: "cog",
      alteredPosition: 0,
    },
  ],
  // day #2
  [
    {
      word: "her",
      hint: "order a pay-___-view",
      answer: "per",
      alteredPosition: 0,
    },
    {
      word: "per",
      hint: "engergizing talk a coach gives",
      answer: "pep",
      alteredPosition: 2,
    },
    {
      word: "pep",
      hint: `opposite of "nope"`,
      answer: "yep",
      alteredPosition: 0,
    },
    {
      word: "yep",
      hint: `slang term for "mouth"`,
      answer: "yap",
      alteredPosition: 1,
    },
    {
      word: "yap",
      hint: "Thanksgiving vegetable",
      answer: "yam",
      alteredPosition: 2,
    },
    {
      word: "yam",
      hint: `delicious!`,
      answer: "yum",
      alteredPosition: 1,
    },
    {
      word: "yum",
      hint: `Big Red, for example`,
      answer: "gum",
      alteredPosition: 0,
    },
    {
      word: "gum",
      hint: `any dude`,
      answer: "guy",
      alteredPosition: 2,
    },
    {
      word: "guy",
      hint: `belly`,
      answer: "gut",
      alteredPosition: 2,
    },
    {
      word: "gut",
      hint: "to chop",
      answer: "cut",
      alteredPosition: 0,
    },
  ],
  // day #3
  [
    {
      word: "has",
      hint: "it's not a solid or a liquid",
      answer: "gas",
      alteredPosition: 0,
    },
    {
      word: "gas",
      hint: "actress who plays Wonder Woman",
      answer: "gal",
      alteredPosition: 2,
    },
    {
      word: "gal",
      hint: "hair styling product",
      answer: "gel",
      alteredPosition: 1,
    },
    {
      word: "gel",
      hint: "delete key label",
      answer: "del",
      alteredPosition: 0,
    },
    {
      word: "del",
      hint: "israel city: ___ Aviv",
      answer: "tel",
      alteredPosition: 0,
    },
    {
      word: "tel",
      hint: "1 + 2 + 3 + 4",
      answer: "ten",
      alteredPosition: 2,
    },
    {
      word: "ten",
      hint: "unit of weight for elephants",
      answer: "ton",
      alteredPosition: 1,
    },
    {
      word: "ton",
      hint: "Jayden, to Will Smith",
      answer: "son",
      alteredPosition: 0,
    },
    {
      word: "son",
      hint: `before "Andreas" or "Antonio"`,
      answer: "san",
      alteredPosition: 1,
    },
    {
      word: "san",
      hint: "moral slip-up",
      answer: "sin",
      alteredPosition: 1,
    },
  ],
  // day #4
  [
    {
      word: "four",
      hint: "unpleasant",
      answer: "foul",
      alteredPosition: 3,
    },
    {
      word: "foul",
      hint: "a fencing sword",
      answer: "foil",
      alteredPosition: 2,
    },
    {
      word: "foil",
      hint: "liquid bubbling",
      answer: "boil",
      alteredPosition: 0,
    },
    {
      word: "boil",
      hint: "to work hard",
      answer: "toil",
      alteredPosition: 0,
    },
    {
      word: "toil",
      hint: "wags when happy",
      answer: "tail",
      alteredPosition: 1,
    },
    {
      word: "tail",
      hint: "trains drive on a ___road",
      answer: "rail",
      alteredPosition: 0,
    },
    {
      word: "rail",
      hint: "military attack, often by air",
      answer: "raid",
      alteredPosition: 3,
    },
    {
      word: "raid",
      hint: "has a bucket and a mop",
      answer: "maid",
      alteredPosition: 0,
    },
    {
      word: "maid",
      hint: "primary",
      answer: "main",
      alteredPosition: 3,
    },
    {
      word: "main",
      hint: "ouch",
      answer: "pain",
      alteredPosition: 0,
    },
  ],
  // day #5
  [
    {
      word: "spit",
      hint: "a common dog name",
      answer: "spot",
      alteredPosition: 2,
    },
    {
      word: "spot",
      hint: "a narrow opening",
      answer: "slot",
      alteredPosition: 1,
    },
    {
      word: "slot",
      hint: "black, powdery substance",
      answer: "soot",
      alteredPosition: 1,
    },
    {
      word: "soot",
      hint: "to cheer",
      answer: "root",
      alteredPosition: 0,
    },
    {
      word: "root",
      hint: "a tall shoe",
      answer: "boot",
      alteredPosition: 0,
    },
    {
      word: "boot",
      hint: "to run away",
      answer: "bolt",
      alteredPosition: 2,
    },
    {
      word: "bolt",
      hint: "worn around the waist",
      answer: "belt",
      alteredPosition: 1,
    },
    {
      word: "belt",
      hint: "dark red vegtable",
      answer: "beet",
      alteredPosition: 2,
    },
    {
      word: "beet",
      hint: "short, high-pitched sound",
      answer: "beep",
      alteredPosition: 3,
    },
    {
      word: "beep",
      hint: "marshmallow treat",
      answer: "peep",
      alteredPosition: 0,
    },
  ],
  // day #6
  [
    {
      word: "run",
      hint: "a religious woman",
      answer: "nun",
      alteredPosition: 0,
    },
    {
      word: "nun",
      hint: "expressing negation or absence",
      answer: "non",
      alteredPosition: 1,
    },
    {
      word: "non",
      hint: "opposite of later",
      answer: "now",
      alteredPosition: 1,
    },
    {
      word: "now",
      hint: "says moo",
      answer: "cow",
      alteredPosition: 0,
    },
    {
      word: "cow",
      hint: "serves and protects",
      answer: "cop",
      alteredPosition: 2,
    },
    {
      word: "cop",
      hint: "washes the floor",
      answer: "mop",
      alteredPosition: 0,
    },
    {
      word: "mop",
      hint: "drawing of an area",
      answer: "map",
      alteredPosition: 1,
    },
    {
      word: "map",
      hint: "sticky, from a tree",
      answer: "sap",
      alteredPosition: 0,
    },
    {
      word: "sap",
      hint: "a tiny drink",
      answer: "sip",
      alteredPosition: 1,
    },
    {
      word: "sip",
      hint: "extra gratitude",
      answer: "tip",
      alteredPosition: 0,
    },
  ],
  // 3/28/2022
  [
    {
      word: "trip",
      hint: "catch an animal",
      answer: "trap",
      alteredPosition: 2,
    },
    {
      word: "trap",
      hint: "ash___",
      answer: "tray",
      alteredPosition: 3,
    },
    {
      word: "tray",
      hint: "religious worship",
      answer: "pray",
      alteredPosition: 0,
    },
    {
      word: "pray",
      hint: "theatrical performance",
      answer: "play",
      alteredPosition: 1,
    },
    {
      word: "play",
      hint: "vanquish",
      answer: "slay",
      alteredPosition: 0,
    },
    {
      word: "slay",
      hint: "strike with your hand",
      answer: "slap",
      alteredPosition: 3,
    },
    {
      word: "slap",
      hint: "accidental fall",
      answer: "slip",
      alteredPosition: 2,
    },
    {
      word: "slip",
      hint: "pig food",
      answer: "slop",
      alteredPosition: 2,
    },
    {
      word: "slop",
      hint: "mall activity",
      answer: "shop",
      alteredPosition: 1,
    },
    {
      word: "shop",
      hint: "large boat",
      answer: "ship",
      alteredPosition: 2,
    },
  ],
  // 3/29/2022 (#7)
  [
    {
      word: "shard",
      hint: "not dull",
      answer: "sharp",
      alteredPosition: 4,
    },
    {
      word: "sharp",
      hint: "a single stock",
      answer: "share",
      alteredPosition: 4,
    },
    {
      word: "share",
      hint: "beach",
      answer: "shore",
      alteredPosition: 2,
    },
    {
      word: "shore",
      hint: "a household task",
      answer: "chore",
      alteredPosition: 0,
    },
    {
      word: "chore",
      hint: "decided",
      answer: "chose",
      alteredPosition: 3,
    },
    {
      word: "chose",
      hint: "nearby",
      answer: "close",
      alteredPosition: 1,
    },
    {
      word: "close",
      hint: "a duplicate",
      answer: "clone",
      alteredPosition: 3,
    },
    {
      word: "clone",
      hint: "garlic measurement",
      answer: "clove",
      alteredPosition: 3,
    },
    {
      word: "clove",
      hint: "a hand covering",
      answer: "glove",
      alteredPosition: 0,
    },
    {
      word: "glove",
      hint: "model of Earth",
      answer: "globe",
      alteredPosition: 3,
    },
  ],
  // 3/30/2022 (#8)
  [
    {
      word: "foot",
      hint: "silly person",
      answer: "fool",
      alteredPosition: 3,
    },
    {
      word: "fool",
      hint: "chilly",
      answer: "cool",
      alteredPosition: 0,
    },
    {
      word: "cool",
      hint: "black rock fuel",
      answer: "coal",
      alteredPosition: 2,
    },
    {
      word: "coal",
      hint: "jacket",
      answer: "coat",
      alteredPosition: 3,
    },
    {
      word: "coat",
      hint: "water vehicle",
      answer: "boat",
      alteredPosition: 0,
    },
    {
      word: "boat",
      hint: "furry pig",
      answer: "boar",
      alteredPosition: 3,
    },
    {
      word: "boar",
      hint: "brown, polar, panda",
      answer: "bear",
      alteredPosition: 1,
    },
    {
      word: "bear",
      hint: "fruit",
      answer: "pear",
      alteredPosition: 0,
    },
    {
      word: "pear",
      hint: "top of a mountain",
      answer: "peak",
      alteredPosition: 3,
    },
    {
      word: "peak",
      hint: "frail",
      answer: "weak",
      alteredPosition: 0,
    },
  ],
  // 3/31/2022 (#9)
  [
    {
      word: "bear",
      hint: "a drop of sweat",
      answer: "bead",
      alteredPosition: 3,
    },
    {
      word: "bead",
      hint: "paint, pipes, pencil",
      answer: "lead",
      alteredPosition: 0,
    },
    {
      word: "lead",
      hint: "divulging information",
      answer: "leak",
      alteredPosition: 3,
    },
    {
      word: "leak",
      hint: "the top",
      answer: "peak",
      alteredPosition: 0,
    },
    {
      word: "peak",
      hint: "a light kiss",
      answer: "peck",
      alteredPosition: 2,
    },
    {
      word: "peck",
      hint: "to punch",
      answer: "deck",
      alteredPosition: 0,
    },
    {
      word: "deck",
      hint: "bringing a boat to a stop",
      answer: "dock",
      alteredPosition: 1,
    },
    {
      word: "dock",
      hint: "a geek",
      answer: "dork",
      alteredPosition: 2,
    },
    {
      word: "dork",
      hint: "pig",
      answer: "pork",
      alteredPosition: 0,
    },
    {
      word: "pork",
      hint: "a harbor",
      answer: "port",
      alteredPosition: 3,
    },
  ],
  // 4/1/2022 (#10)
  [
    {
      word: "love",
      hint: "white bird",
      answer: "dove",
      alteredPosition: 0,
    },
    {
      word: "dove",
      hint: "intentional fall",
      answer: "dive",
      alteredPosition: 1,
    },
    {
      word: "dive",
      hint: "honey home",
      answer: "hive",
      alteredPosition: 0,
    },
    {
      word: "hive",
      hint: "nature walk",
      answer: "hike",
      alteredPosition: 2,
    },
    {
      word: "hike",
      hint: "two wheels",
      answer: "bike",
      alteredPosition: 0,
    },
    {
      word: "bike",
      hint: "cook in an oven",
      answer: "bake",
      alteredPosition: 1,
    },
    {
      word: "bake",
      hint: "a bundle of hay",
      answer: "bale",
      alteredPosition: 2,
    },
    {
      word: "bale",
      hint: "gets thrown, kicked, or hit",
      answer: "ball",
      alteredPosition: 3,
    },
    {
      word: "ball",
      hint: "ointment to heal skin",
      answer: "balm",
      alteredPosition: 3,
    },
    {
      word: "balm",
      hint: "tranquil",
      answer: "calm",
      alteredPosition: 0,
    },
  ],
  // 4/2/2022 (#11)
  [
    {
      word: "drop",
      hint: "trickle",
      answer: "drip",
      alteredPosition: 2,
    },
    {
      word: "drip",
      hint: "journey",
      answer: "trip",
      alteredPosition: 0,
    },
    {
      word: "trip",
      hint: "shorten",
      answer: "trim",
      alteredPosition: 3,
    },
    {
      word: "trim",
      hint: "trolley",
      answer: "tram",
      alteredPosition: 2,
    },
    {
      word: "tram",
      hint: "sports group",
      answer: "team",
      alteredPosition: 1,
    },
    {
      word: "team",
      hint: "laser",
      answer: "beam",
      alteredPosition: 0,
    },
    {
      word: "beam",
      hint: "a drop of liquid",
      answer: "bead",
      alteredPosition: 3,
    },
    {
      word: "bead",
      hint: "curve",
      answer: "bend",
      alteredPosition: 2,
    },
    {
      word: "bend",
      hint: "fix",
      answer: "mend",
      alteredPosition: 0,
    },
    {
      word: "mend",
      hint: "brain",
      answer: "mind",
      alteredPosition: 1,
    },
  ],
  // 4/3/2022 (#12)
  [
    {
      word: "fire",
      hint: "to employ",
      answer: "hire",
      alteredPosition: 0,
    },
    {
      word: "hire",
      hint: "a bunny",
      answer: "hare",
      alteredPosition: 1,
    },
    {
      word: "hare",
      hint: "to injure",
      answer: "harm",
      alteredPosition: 3,
    },
    {
      word: "harm",
      hint: "Old MacDonald had one",
      answer: "farm",
      alteredPosition: 0,
    },
    {
      word: "farm",
      hint: "to shape",
      answer: "form",
      alteredPosition: 1,
    },
    {
      word: "form",
      hint: "animal with no arms, legs, or bones",
      answer: "worm",
      alteredPosition: 0,
    },
    {
      word: "worm",
      hint: "perform a job",
      answer: "work",
      alteredPosition: 3,
    },
    {
      word: "work",
      hint: "meat from a pig",
      answer: "pork",
      alteredPosition: 0,
    },
    {
      word: "pork",
      hint: "dock ships",
      answer: "port",
      alteredPosition: 3,
    },
    {
      word: "port",
      hint: "frown",
      answer: "pout",
      alteredPosition: 2,
    },
  ],
  // 4/4/2022 (#13)
  [
    {
      word: "rope",
      hint: "be sad",
      answer: "mope",
      alteredPosition: 0,
    },
    {
      word: "mope",
      hint: "mean, median, ___",
      answer: "mode",
      alteredPosition: 2,
    },
    {
      word: "mode",
      hint: "computer program",
      answer: "code",
      alteredPosition: 0,
    },
    {
      word: "code",
      hint: "ice cream wafer container",
      answer: "cone",
      alteredPosition: 2,
    },
    {
      word: "cone",
      hint: "walking stick",
      answer: "cane",
      alteredPosition: 1,
    },
    {
      word: "cane",
      hint: "birthday, for example",
      answer: "cake",
      alteredPosition: 2,
    },
    {
      word: "cake",
      hint: "rise up",
      answer: "wake",
      alteredPosition: 0,
    },
    {
      word: "wake",
      hint: "goods and merchandise",
      answer: "ware",
      alteredPosition: 2,
    },
    {
      word: "ware",
      hint: "benign growth",
      answer: "wart",
      alteredPosition: 3,
    },
    {
      word: "wart",
      hint: "sour",
      answer: "tart",
      alteredPosition: 0,
    },
  ],
  // 4/5/2022 (#14)
  [
    {
      word: "bun",
      hint: "type of joke",
      answer: "pun",
      alteredPosition: 0,
    },
    {
      word: "pun",
      hint: "a young dog",
      answer: "pup",
      alteredPosition: 2,
    },
    {
      word: "pup",
      hint: "a drinking receptacle",
      answer: "cup",
      alteredPosition: 0,
    },
    {
      word: "cup",
      hint: "a kind of hat",
      answer: "cap",
      alteredPosition: 1,
    },
    {
      word: "cap",
      hint: "a taxi",
      answer: "cab",
      alteredPosition: 2,
    },
    {
      word: "cab",
      hint: "to steal",
      answer: "nab",
      alteredPosition: 0,
    },
    {
      word: "nab",
      hint: "a science place",
      answer: "lab",
      alteredPosition: 0,
    },
    {
      word: "lab",
      hint: "a toss",
      answer: "lob",
      alteredPosition: 1,
    },
    {
      word: "lob",
      hint: "to float long",
      answer: "bob",
      alteredPosition: 0,
    },
    {
      word: "bob",
      hint: "a ghost says",
      answer: "boo",
      alteredPosition: 2,
    },
  ],
  // 4/6/2022 (#15)
  [
    {
      word: "vat",
      hint: "wear it upon your head",
      answer: "hat",
      alteredPosition: 0,
    },
    {
      word: "hat",
      hint: "high temperature",
      answer: "hot",
      alteredPosition: 1,
    },
    {
      word: "hot",
      hint: "an owl says",
      answer: "hoo",
      alteredPosition: 2,
    },
    {
      word: "hoo",
      hint: "a cow says",
      answer: "moo",
      alteredPosition: 0,
    },
    {
      word: "moo",
      hint: "Larry, Curly, and ___",
      answer: "moe",
      alteredPosition: 2,
    },
    {
      word: "moe",
      hint: "a female deer",
      answer: "doe",
      alteredPosition: 0,
    },
    {
      word: "doe",
      hint: "singlular form of dice",
      answer: "die",
      alteredPosition: 1,
    },
    {
      word: "die",
      hint: "to compete",
      answer: "vie",
      alteredPosition: 0,
    },
    {
      word: "vie",
      hint: "a special guest",
      answer: "vip",
      alteredPosition: 2,
    },
    {
      word: "vip",
      hint: "a hint",
      answer: "tip",
      alteredPosition: 0,
    },
  ],
  // 4/7/2022 (#16)
  [
    {
      word: "copy",
      hint: "deal with",
      answer: "cope",
      alteredPosition: 3,
    },
    {
      word: "cope",
      hint: "arrive",
      answer: "come",
      alteredPosition: 2,
    },
    {
      word: "come",
      hint: "a circular roof",
      answer: "dome",
      alteredPosition: 0,
    },
    {
      word: "dome",
      hint: "10 cent coin",
      answer: "dime",
      alteredPosition: 1,
    },
    {
      word: "dime",
      hint: "a green citrus fruit",
      answer: "lime",
      alteredPosition: 0,
    },
    {
      word: "lime",
      hint: "existence",
      answer: "life",
      alteredPosition: 2,
    },
    {
      word: "life",
      hint: "to carry",
      answer: "lift",
      alteredPosition: 3,
    },
    {
      word: "lift",
      hint: "attic",
      answer: "loft",
      alteredPosition: 1,
    },
    {
      word: "loft",
      hint: "missing",
      answer: "lost",
      alteredPosition: 2,
    },
    {
      word: "lost",
      hint: "mail",
      answer: "post",
      alteredPosition: 0,
    },
  ],
  // 4/8/2022 (#17)
  [
    {
      word: "womb",
      hint: "hair brush",
      answer: "comb",
      alteredPosition: 0,
    },
    {
      word: "comb",
      hint: "to give away for free",
      answer: "comp",
      alteredPosition: 3,
    },
    {
      word: "comp",
      hint: "outdoor living",
      answer: "camp",
      alteredPosition: 1,
    },
    {
      word: "camp",
      hint: "slightly wet",
      answer: "damp",
      alteredPosition: 0,
    },
    {
      word: "damp",
      hint: "woman of rank",
      answer: "dame",
      alteredPosition: 3,
    },
    {
      word: "dame",
      hint: "domesticated",
      answer: "tame",
      alteredPosition: 0,
    },
    {
      word: "tame",
      hint: "clock",
      answer: "time",
      alteredPosition: 1,
    },
    {
      word: "time",
      hint: "copy",
      answer: "mime",
      alteredPosition: 0,
    },
    {
      word: "mime",
      hint: "5,280 feet, 1,600 meters",
      answer: "mile",
      alteredPosition: 2,
    },
    {
      word: "mile",
      hint: "evil",
      answer: "vile",
      alteredPosition: 0,
    },
  ],
  // 4/9/2022 (#18)
  [
    {
      word: "rad",
      hint: "to remove",
      answer: "rid",
      alteredPosition: 1,
    },
    {
      word: "rid",
      hint: "a cover",
      answer: "lid",
      alteredPosition: 0,
    },
    {
      word: "lid",
      hint: "a boy",
      answer: "lad",
      alteredPosition: 1,
    },
    {
      word: "lad",
      hint: "the rules",
      answer: "law",
      alteredPosition: 2,
    },
    {
      word: "law",
      hint: "uncooked",
      answer: "raw",
      alteredPosition: 0,
    },
    {
      word: "raw",
      hint: "to paddle",
      answer: "row",
      alteredPosition: 1,
    },
    {
      word: "row",
      hint: "shoots arrows",
      answer: "bow",
      alteredPosition: 0,
    },
    {
      word: "bow",
      hint: "wet, muddy ground",
      answer: "bog",
      alteredPosition: 2,
    },
    {
      word: "bog",
      hint: "a tiny insect",
      answer: "bug",
      alteredPosition: 1,
    },
    {
      word: "bug",
      hint: "to pull",
      answer: "tug",
      alteredPosition: 0,
    },
  ],
  // 4/10/2022 (#19)
  [
    {
      word: "ref",
      hint: "color of a stop sign",
      answer: "red",
      alteredPosition: 2,
    },
    {
      word: "red",
      hint: "a place to sleep",
      answer: "bed",
      alteredPosition: 0,
    },
    {
      word: "bed",
      hint: "honey maker",
      answer: "bee",
      alteredPosition: 2,
    },
    {
      word: "bee",
      hint: "a type of shirt",
      answer: "tee",
      alteredPosition: 0,
    },
    {
      word: "tee",
      hint: "a foot finger",
      answer: "toe",
      alteredPosition: 1,
    },
    {
      word: "toe",
      hint: "fish eggs",
      answer: "roe",
      alteredPosition: 0,
    },
    {
      word: "roe",
      hint: "a type of grain",
      answer: "rye",
      alteredPosition: 1,
    },
    {
      word: "rye",
      hint: "used to add color",
      answer: "dye",
      alteredPosition: 0,
    },
    {
      word: "dye",
      hint: "hole in a needle",
      answer: "eye",
      alteredPosition: 0,
    },
    {
      word: "eye",
      hint: "a female sheep",
      answer: "ewe",
      alteredPosition: 1,
    },
  ],
  // 4/11/2022 (#20)
  [
    {
      word: "son",
      hint: "center of the solar system",
      answer: "sun",
      alteredPosition: 1,
    },
    {
      word: "sun",
      hint: "offense or fault",
      answer: "sin",
      alteredPosition: 1,
    },
    {
      word: "sin",
      hint: "___ and tonic",
      answer: "gin",
      alteredPosition: 0,
    },
    {
      word: "gin",
      hint: "a weapon",
      answer: "gun",
      alteredPosition: 1,
    },
    {
      word: "gun",
      hint: "stomach",
      answer: "gut",
      alteredPosition: 2,
    },
    {
      word: "gut",
      hint: "shack",
      answer: "hut",
      alteredPosition: 0,
    },
    {
      word: "hut",
      hint: "headgear",
      answer: "hat",
      alteredPosition: 1,
    },
    {
      word: "hat",
      hint: "feline",
      answer: "cat",
      alteredPosition: 0,
    },
    {
      word: "cat",
      hint: "a bed",
      answer: "cot",
      alteredPosition: 1,
    },
    {
      word: "cot",
      hint: "a cooking container",
      answer: "pot",
      alteredPosition: 0,
    },
  ],
];
