export const game = [
  // day #1
  [
    {
      word: "woo",
      hint: "stir frying pan",
      answer: "wok",
      alteredPosition: 2,
    },
    {
      word: "wok",
      hint: "took the championship",
      answer: "won",
      alteredPosition: 2,
    },
    {
      word: "won",
      hint: `dramatic cry: "___ is me!"`,
      answer: "woe",
      alteredPosition: 2,
    },
    {
      word: "woe",
      hint: "long-handled farm tool",
      answer: "hoe",
      alteredPosition: 0,
    },
    {
      word: "hoe",
      hint: "move like a kangaroo",
      answer: "hop",
      alteredPosition: 2,
    },
    {
      word: "hop",
      hint: `after "alley" in basketball`,
      answer: "oop",
      alteredPosition: 0,
    },
    {
      word: "oop",
      hint: `pairs with an audience "aah"`,
      answer: "ooh",
      alteredPosition: 2,
    },
    {
      word: "ooh",
      hint: `modeling toy: play-___`,
      answer: "doh",
      alteredPosition: 0,
    },
    {
      word: "doh",
      hint: "Lassie is one",
      answer: "dog",
      alteredPosition: 2,
    },
    {
      word: "dog",
      hint: "gear tooth",
      answer: "cog",
      alteredPosition: 0,
    },
  ],
  // day #2
  [
    {
      word: "her",
      hint: "order a pay-___-view",
      answer: "per",
      alteredPosition: 0,
    },
    {
      word: "per",
      hint: "engergizing talk a coach gives",
      answer: "pep",
      alteredPosition: 2,
    },
    {
      word: "pep",
      hint: `opposite of "nope"`,
      answer: "yep",
      alteredPosition: 0,
    },
    {
      word: "yep",
      hint: `slang term for "mouth"`,
      answer: "yap",
      alteredPosition: 1,
    },
    {
      word: "yap",
      hint: "Thanksgiving vegetable",
      answer: "yam",
      alteredPosition: 2,
    },
    {
      word: "yam",
      hint: `delicious!`,
      answer: "yum",
      alteredPosition: 1,
    },
    {
      word: "yum",
      hint: `Big Red, for example`,
      answer: "gum",
      alteredPosition: 0,
    },
    {
      word: "gum",
      hint: `any dude`,
      answer: "guy",
      alteredPosition: 2,
    },
    {
      word: "guy",
      hint: `belly`,
      answer: "gut",
      alteredPosition: 2,
    },
    {
      word: "gut",
      hint: "to chop",
      answer: "cut",
      alteredPosition: 0,
    },
  ],
  // day #3
  [
    {
      word: "has",
      hint: "it's not a solid or a liquid",
      answer: "gas",
      alteredPosition: 0,
    },
    {
      word: "gas",
      hint: "actress who plays Wonder Woman",
      answer: "gal",
      alteredPosition: 2,
    },
    {
      word: "gal",
      hint: "hair styling product",
      answer: "gel",
      alteredPosition: 1,
    },
    {
      word: "gel",
      hint: "delete key label",
      answer: "del",
      alteredPosition: 0,
    },
    {
      word: "del",
      hint: "israel city: ___ Aviv",
      answer: "tel",
      alteredPosition: 0,
    },
    {
      word: "tel",
      hint: "1 + 2 + 3 + 4",
      answer: "ten",
      alteredPosition: 2,
    },
    {
      word: "ten",
      hint: "unit of weight for elephants",
      answer: "ton",
      alteredPosition: 1,
    },
    {
      word: "ton",
      hint: "Jayden, to Will Smith",
      answer: "son",
      alteredPosition: 0,
    },
    {
      word: "son",
      hint: `before "Andreas" or "Antonio"`,
      answer: "san",
      alteredPosition: 1,
    },
    {
      word: "san",
      hint: "moral slip-up",
      answer: "sin",
      alteredPosition: 1,
    },
  ],
  // day #4
  [
    {
      word: "four",
      hint: "unpleasant",
      answer: "foul",
      alteredPosition: 3,
    },
    {
      word: "foul",
      hint: "a fencing sword",
      answer: "foil",
      alteredPosition: 2,
    },
    {
      word: "foil",
      hint: "liquid bubbling",
      answer: "boil",
      alteredPosition: 0,
    },
    {
      word: "boil",
      hint: "to work hard",
      answer: "toil",
      alteredPosition: 0,
    },
    {
      word: "toil",
      hint: "wags when happy",
      answer: "tail",
      alteredPosition: 1,
    },
    {
      word: "tail",
      hint: "trains drive on a ___road",
      answer: "rail",
      alteredPosition: 0,
    },
    {
      word: "rail",
      hint: "military attack, often by air",
      answer: "raid",
      alteredPosition: 3,
    },
    {
      word: "raid",
      hint: "has a bucket and a mop",
      answer: "maid",
      alteredPosition: 0,
    },
    {
      word: "maid",
      hint: "primary",
      answer: "main",
      alteredPosition: 3,
    },
    {
      word: "main",
      hint: "ouch",
      answer: "pain",
      alteredPosition: 0,
    },
  ],
  // day #5
  [
    {
      word: "spit",
      hint: "a common dog name",
      answer: "spot",
      alteredPosition: 2,
    },
    {
      word: "spot",
      hint: "a narrow opening",
      answer: "slot",
      alteredPosition: 1,
    },
    {
      word: "slot",
      hint: "black, powdery substance",
      answer: "soot",
      alteredPosition: 1,
    },
    {
      word: "soot",
      hint: "to cheer",
      answer: "root",
      alteredPosition: 0,
    },
    {
      word: "root",
      hint: "a tall shoe",
      answer: "boot",
      alteredPosition: 0,
    },
    {
      word: "boot",
      hint: "to run away",
      answer: "bolt",
      alteredPosition: 2,
    },
    {
      word: "bolt",
      hint: "worn around the waist",
      answer: "belt",
      alteredPosition: 1,
    },
    {
      word: "belt",
      hint: "dark red vegtable",
      answer: "beet",
      alteredPosition: 2,
    },
    {
      word: "beet",
      hint: "short, high-pitched sound",
      answer: "beep",
      alteredPosition: 3,
    },
    {
      word: "beep",
      hint: "marshmallow treat",
      answer: "peep",
      alteredPosition: 0,
    },
  ],
  // day #6
  [
    {
      word: "run",
      hint: "a religious woman",
      answer: "nun",
      alteredPosition: 0,
    },
    {
      word: "nun",
      hint: "expressing negation or absence",
      answer: "non",
      alteredPosition: 1,
    },
    {
      word: "non",
      hint: "opposite of later",
      answer: "now",
      alteredPosition: 1,
    },
    {
      word: "now",
      hint: "says moo",
      answer: "cow",
      alteredPosition: 0,
    },
    {
      word: "cow",
      hint: "serves and protects",
      answer: "cop",
      alteredPosition: 2,
    },
    {
      word: "cop",
      hint: "washes the floor",
      answer: "mop",
      alteredPosition: 0,
    },
    {
      word: "mop",
      hint: "drawing of an area",
      answer: "map",
      alteredPosition: 1,
    },
    {
      word: "map",
      hint: "sticky, from a tree",
      answer: "sap",
      alteredPosition: 0,
    },
    {
      word: "sap",
      hint: "a tiny drink",
      answer: "sip",
      alteredPosition: 1,
    },
    {
      word: "sip",
      hint: "extra gratitude",
      answer: "tip",
      alteredPosition: 0,
    },
  ],
];
